version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/apps/website"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/apps/dashboard"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/packages/database"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/packages/eslint-config"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/packages/typescript-config"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"