export const env = {
  // Required
  NEXT_PUBLIC_MERCHANT_NAME: process.env.NEXT_PUBLIC_MERCHANT_NAME!,
  NEXT_PUBLIC_MERCHANT_EMAIL: process.env.NEXT_PUBLIC_MERCHANT_EMAIL!,
  NEXT_PUBLIC_SITE_ENV: process.env.NEXT_PUBLIC_SITE_ENV!,
  NEXT_PUBLIC_PAYPLUG_SECRET_KEY: process.env.NEXT_PUBLIC_PAYPLUG_SECRET_KEY!,
  NEXT_PUBLIC_SIB_API_KEY: process.env.NEXT_PUBLIC_SIB_API_KEY!,

  // Optional
  GOOGLE_TAG_MANAGER_ID: process.env.GOOGLE_TAG_MANAGER_ID,
  NEXT_PUBLIC_WEBSITE_URL: process.env.NEXT_PUBLIC_WEBSITE_URL,
  NEXT_PUBLIC_VERCEL_URL: process.env.NEXT_PUBLIC_VERCEL_URL,

  // Custom
  isDev: process.env.NODE_ENV === 'development',
};
